<?php

namespace Lle\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RejetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RejetRepository extends EntityRepository{
    //put your code here
}
