services:

    _defaults:
        autowire: true
        public: false
        autoconfigure: true


    Lle\MailerBundle\Service\MailerManager:
        arguments: ["@doctrine.orm.default_entity_manager", "@router", "@mailer", "@twig", "@parameter_bag"]
